package org.punit.exception;

public class TestRunningException extends RuntimeException {

    public TestRunningException(Throwable cause) {
        super(cause);
    }

}
